"""Discovery and adapter resolution for CloudSentinel detector plugins."""

from .contracts import (
    ArtifactResult,
    DetectorAdapter,
    DetectorCompatibilityError,
    DetectorExecutionError,
    DetectorPromotionError,
    DetectorTrainingError,
    ProgressReporter,
    PluginReference,
    PromotionResult,
    TrainableDetectorAdapter,
    TrainingContext,
    TrainingData,
    TrainingResult,
)
from .registry import (
    AdapterContractError,
    AdapterImportError,
    InvalidEntryPointError,
    ManifestValidationError,
    ParameterValidationError,
    UnsupportedTrainingProtocolError,
    UnknownDetectorError,
    discover_detectors,
    get_adapter,
    get_descriptor,
    get_manifest,
    get_plugin_reference,
    get_training_adapter,
    load_manifest,
    scan_detectors,
    validate_training_parameters,
)

__all__ = [
    "AdapterContractError",
    "AdapterImportError",
    "ArtifactResult",
    "DetectorAdapter",
    "DetectorCompatibilityError",
    "DetectorExecutionError",
    "DetectorPromotionError",
    "DetectorTrainingError",
    "InvalidEntryPointError",
    "ManifestValidationError",
    "ParameterValidationError",
    "ProgressReporter",
    "PluginReference",
    "PromotionResult",
    "TrainableDetectorAdapter",
    "TrainingContext",
    "TrainingData",
    "TrainingResult",
    "UnknownDetectorError",
    "UnsupportedTrainingProtocolError",
    "discover_detectors",
    "get_adapter",
    "get_descriptor",
    "get_manifest",
    "get_plugin_reference",
    "get_training_adapter",
    "load_manifest",
    "scan_detectors",
    "validate_training_parameters",
]
