apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion-deployment
  namespace: cloudsentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-ingestion
  template:
    metadata:
      labels:
        app: data-ingestion
    spec:
      serviceAccountName: data-ingestion-sa  # Ensure this is set correctly
      securityContext:
        fsGroup: 10001
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: data-ingestion
        image: jojojochem/data_ingestion:dc-infra-1
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10001
          runAsGroup: 10001
        ports:
        - name: http
          containerPort: 5001
        env:
        - name: CATALOGUE_STORAGE_ROOT
          value: "/app/storage/catalogue"
        - name: CATALOGUE_CLUSTER_DEFAULT_PROMETHEUS_URL
          value: "http://prometheus-server.monitoring.svc.cluster.local:80"
        - name: CELERY_BROKER_URL
          value: "redis://redis.cloudsentinel.svc.cluster.local:6379/0"
        - name: CELERY_RESULT_BACKEND
          value: "redis://redis.cloudsentinel.svc.cluster.local:6379/0"
        volumeMounts:
        - name: catalogue-storage
          mountPath: /app/storage
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 3
      volumes:
      - name: catalogue-storage
        persistentVolumeClaim:
          claimName: data-catalogue-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: data-ingestion-service
  namespace: cloudsentinel
spec:
  selector:
    app: data-ingestion
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-ingestion-sa
  namespace: cloudsentinel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cloudsentinel
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: cloudsentinel
subjects:
- kind: ServiceAccount
  name: data-ingestion-sa
  namespace: cloudsentinel
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods-global
subjects:
- kind: ServiceAccount
  name: data-ingestion-sa
  namespace: cloudsentinel
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
